const langs = {
    "hljs 1c": "1C:Enterprise",
    "hljs abnf": "Augmented Backus-Naur Form",
    "hljs accesslog": "Apache Access Log",
    "hljs actionscript": "ActionScript",
    "hljs as": "ActionScript",
    "hljs ada": "Ada",
    "hljs angelscript": "AngelScript",
    "hljs asc": "AngelScript",
    "hljs apache": "Apache config",
    "hljs apacheconf": "Apache config",
    "hljs applescript": "AppleScript",
    "hljs osascript": "AppleScript",
    "hljs arcade": "ArcGIS Arcade",
    "hljs arduino": "Arduino",
    "hljs ino": "Arduino",
    "hljs armasm": "ARM Assembly",
    "hljs arm": "ARM Assembly",
    "hljs asciidoc": "AsciiDoc",
    "hljs adoc": "AsciiDoc",
    "hljs aspectj": "AspectJ",
    "hljs autohotkey": "AutoHotkey",
    "hljs ahk": "AutoHotkey",
    "hljs autoit": "AutoIt",
    "hljs avrasm": "AVR Assembly",
    "hljs awk": "Awk",
    "hljs axapta": "X++",
    "hljs x++": "X++",
    "hljs bash": "Bash",
    "hljs sh": "Bash",
    "hljs zsh": "Bash",
    "hljs basic": "BASIC",
    "hljs bnf": "Backus–Naur Form",
    "hljs brainfuck": "Brainfuck",
    "hljs bf": "Brainfuck",
    "hljs c": "C",
    "hljs h": "C",
    "hljs cal": "C/AL",
    "hljs capnproto": "Cap’n Proto",
    "hljs capnp": "Cap’n Proto",
    "hljs ceylon": "Ceylon",
    "hljs clean": "Clean",
    "hljs icl": "Clean",
    "hljs dcl": "Clean",
    "hljs clojure": "Clojure",
    "hljs clj": "Clojure",
    "hljs edn": "Clojure",
    "hljs clojure-repl": "Clojure REPL",
    "hljs cmake": "CMake",
    "hljs cmake.in": "CMake",
    "hljs coffeescript": "CoffeeScript",
    "hljs coffee": "CoffeeScript",
    "hljs cson": "CoffeeScript",
    "hljs iced": "CoffeeScript",
    "hljs coq": "Coq",
    "hljs cos": "Caché Object Script",
    "hljs cls": "Caché Object Script",
    "hljs cpp": "C++",
    "hljs cc": "C++",
    "hljs c++": "C++",
    "hljs h++": "C++",
    "hljs hpp": "C++",
    "hljs hh": "C++",
    "hljs hxx": "C++",
    "hljs cxx": "C++",
    "hljs crmsh": "crmsh",
    "hljs crm": "crmsh",
    "hljs pcmk": "crmsh",
    "hljs crystal": "Crystal",
    "hljs cr": "Crystal",
    "hljs csharp": "C#",
    "hljs cs": "C#",
    "hljs c#": "C#",
    "hljs csp": "CSP",
    "hljs css": "CSS",
    "hljs d": "D",
    "hljs dart": "Dart",
    "hljs delphi": "Delphi",
    "hljs dpr": "Delphi",
    "hljs dfm": "Delphi",
    "hljs pas": "Delphi",
    "hljs pascal": "Delphi",
    "hljs diff": "Diff",
    "hljs patch": "Diff",
    "hljs django": "Django",
    "hljs jinja": "Django",
    "hljs dns": "DNS Zone",
    "hljs bind": "DNS Zone",
    "hljs zone": "DNS Zone",
    "hljs dockerfile": "Dockerfile",
    "hljs docker": "Dockerfile",
    "hljs dos": "Batch file (DOS)",
    "hljs bat": "Batch file (DOS)",
    "hljs cmd": "Batch file (DOS)",
    "hljs dsconfig": "undefined",
    "hljs dts": "Device Tree",
    "hljs dust": "Dust",
    "hljs dst": "Dust",
    "hljs ebnf": "Extended Backus-Naur Form",
    "hljs elixir": "Elixir",
    "hljs ex": "Elixir",
    "hljs exs": "Elixir",
    "hljs elm": "Elm",
    "hljs erb": "ERB",
    "hljs erlang": "Erlang",
    "hljs erl": "Erlang",
    "hljs erlang-repl": "Erlang REPL",
    "hljs excel": "Excel formulae",
    "hljs xlsx": "Excel formulae",
    "hljs xls": "Excel formulae",
    "hljs fix": "FIX",
    "hljs flix": "Flix",
    "hljs fortran": "Fortran",
    "hljs f90": "Fortran",
    "hljs f95": "Fortran",
    "hljs fsharp": "F#",
    "hljs fs": "F#",
    "hljs f#": "F#",
    "hljs gams": "GAMS",
    "hljs gms": "GAMS",
    "hljs gauss": "GAUSS",
    "hljs gss": "GAUSS",
    "hljs gcode": "G-code (ISO 6983)",
    "hljs nc": "G-code (ISO 6983)",
    "hljs gherkin": "Gherkin",
    "hljs feature": "Gherkin",
    "hljs glsl": "GLSL",
    "hljs gml": "GML",
    "hljs go": "Go",
    "hljs golang": "Go",
    "hljs golo": "Golo",
    "hljs gradle": "Gradle",
    "hljs graphql": "GraphQL",
    "hljs gql": "GraphQL",
    "hljs groovy": "Groovy",
    "hljs haml": "HAML",
    "hljs handlebars": "Handlebars",
    "hljs hbs": "Handlebars",
    "hljs html.hbs": "Handlebars",
    "hljs html.handlebars": "Handlebars",
    "hljs htmlbars": "Handlebars",
    "hljs haskell": "Haskell",
    "hljs hs": "Haskell",
    "hljs haxe": "Haxe",
    "hljs hx": "Haxe",
    "hljs hsp": "HSP",
    "hljs http": "HTTP",
    "hljs https": "HTTP",
    "hljs hy": "Hy",
    "hljs hylang": "Hy",
    "hljs inform7": "Inform 7",
    "hljs i7": "Inform 7",
    "hljs ini": "TOML, also INI",
    "hljs toml": "TOML, also INI",
    "hljs irpf90": "IRPF90",
    "hljs isbl": "ISBL",
    "hljs java": "Java",
    "hljs jsp": "Java",
    "hljs javascript": "JavaScript",
    "hljs js": "JavaScript",
    "hljs jsx": "JavaScript",
    "hljs mjs": "JavaScript",
    "hljs cjs": "JavaScript",
    "hljs jboss-cli": "JBoss CLI",
    "hljs wildfly-cli": "JBoss CLI",
    "hljs json": "JSON",
    "hljs jsonc": "JSON",
    "hljs julia": "Julia",
    "hljs julia-repl": "Julia REPL",
    "hljs jldoctest": "Julia REPL",
    "hljs kotlin": "Kotlin",
    "hljs kt": "Kotlin",
    "hljs kts": "Kotlin",
    "hljs lasso": "Lasso",
    "hljs ls": "LiveScript",
    "hljs lassoscript": "Lasso",
    "hljs latex": "LaTeX",
    "hljs tex": "LaTeX",
    "hljs ldif": "LDIF",
    "hljs leaf": "Leaf",
    "hljs less": "Less",
    "hljs lisp": "Lisp",
    "hljs livecodeserver": "LiveCode",
    "hljs livescript": "LiveScript",
    "hljs llvm": "LLVM IR",
    "hljs lsl": "LSL (Linden Scripting Language)",
    "hljs lua": "Lua",
    "hljs pluto": "Lua",
    "hljs makefile": "Makefile",
    "hljs mk": "Makefile",
    "hljs mak": "Makefile",
    "hljs make": "Makefile",
    "hljs markdown": "Markdown",
    "hljs md": "Markdown",
    "hljs mkdown": "Markdown",
    "hljs mkd": "Markdown",
    "hljs mathematica": "Mathematica",
    "hljs mma": "Mathematica",
    "hljs wl": "Mathematica",
    "hljs matlab": "Matlab",
    "hljs maxima": "Maxima",
    "hljs mel": "MEL",
    "hljs mercury": "Mercury",
    "hljs m": "Mercury",
    "hljs moo": "Mercury",
    "hljs mipsasm": "MIPS Assembly",
    "hljs mips": "MIPS Assembly",
    "hljs mizar": "Mizar",
    "hljs mojolicious": "Mojolicious",
    "hljs monkey": "Monkey",
    "hljs moonscript": "MoonScript",
    "hljs moon": "MoonScript",
    "hljs n1ql": "N1QL",
    "hljs nestedtext": "Nested Text",
    "hljs nt": "Nested Text",
    "hljs nginx": "Nginx config",
    "hljs nginxconf": "Nginx config",
    "hljs nim": "Nim",
    "hljs nix": "Nix",
    "hljs nixos": "Nix",
    "hljs node-repl": "Node REPL",
    "hljs nsis": "NSIS",
    "hljs objectivec": "Objective-C",
    "hljs mm": "Objective-C",
    "hljs objc": "Objective-C",
    "hljs obj-c": "Objective-C",
    "hljs obj-c++": "Objective-C",
    "hljs objective-c++": "Objective-C",
    "hljs ocaml": "OCaml",
    "hljs ml": "OCaml",
    "hljs openscad": "OpenSCAD",
    "hljs scad": "OpenSCAD",
    "hljs oxygene": "Oxygene",
    "hljs parser3": "Parser3",
    "hljs perl": "Perl",
    "hljs pl": "Perl",
    "hljs pm": "Perl",
    "hljs pf": "Packet Filter config",
    "hljs pf.conf": "Packet Filter config",
    "hljs pgsql": "PostgreSQL",
    "hljs postgres": "PostgreSQL",
    "hljs postgresql": "PostgreSQL",
    "hljs php": "undefined",
    "hljs php-template": "PHP template",
    "hljs plaintext": "Plain text",
    "hljs text": "Plain text",
    "hljs txt": "Plain text",
    "hljs pony": "Pony",
    "hljs powershell": "PowerShell",
    "hljs pwsh": "PowerShell",
    "hljs ps": "PowerShell",
    "hljs ps1": "PowerShell",
    "hljs processing": "Processing",
    "hljs pde": "Processing",
    "hljs profile": "Python profiler",
    "hljs prolog": "Prolog",
    "hljs properties": ".properties",
    "hljs protobuf": "Protocol Buffers",
    "hljs proto": "Protocol Buffers",
    "hljs puppet": "Puppet",
    "hljs pp": "Puppet",
    "hljs purebasic": "PureBASIC",
    "hljs pb": "PureBASIC",
    "hljs pbi": "PureBASIC",
    "hljs python": "Python",
    "hljs py": "Python",
    "hljs gyp": "Python",
    "hljs ipython": "Python",
    "hljs python-repl": "undefined",
    "hljs pycon": "undefined",
    "hljs q": "Q",
    "hljs k": "Q",
    "hljs kdb": "Q",
    "hljs qml": "QML",
    "hljs qt": "QML",
    "hljs r": "R",
    "hljs reasonml": "ReasonML",
    "hljs re": "ReasonML",
    "hljs rib": "RenderMan RIB",
    "hljs roboconf": "Roboconf",
    "hljs graph": "Roboconf",
    "hljs instances": "Roboconf",
    "hljs routeros": "MikroTik RouterOS script",
    "hljs mikrotik": "MikroTik RouterOS script",
    "hljs rsl": "RenderMan RSL",
    "hljs ruby": "Ruby",
    "hljs rb": "Ruby",
    "hljs gemspec": "Ruby",
    "hljs podspec": "Ruby",
    "hljs thor": "Ruby",
    "hljs irb": "Ruby",
    "hljs ruleslanguage": "Oracle Rules Language",
    "hljs rust": "Rust",
    "hljs rs": "Rust",
    "hljs sas": "SAS",
    "hljs scala": "Scala",
    "hljs scheme": "Scheme",
    "hljs scm": "Scheme",
    "hljs scilab": "Scilab",
    "hljs sci": "Scilab",
    "hljs scss": "SCSS",
    "hljs shell": "Shell Session",
    "hljs console": "Shell Session",
    "hljs shellsession": "Shell Session",
    "hljs smali": "Smali",
    "hljs smalltalk": "Smalltalk",
    "hljs sml": "SML (Standard ML)",
    "hljs sqf": "SQF",
    "hljs sql": "SQL",
    "hljs stan": "Stan",
    "hljs stanfuncs": "Stan",
    "hljs stata": "Stata",
    "hljs do": "Stata",
    "hljs ado": "Stata",
    "hljs step21": "STEP Part 21",
    "hljs p21": "STEP Part 21",
    "hljs step": "STEP Part 21",
    "hljs stp": "STEP Part 21",
    "hljs stylus": "Stylus",
    "hljs styl": "Stylus",
    "hljs subunit": "SubUnit",
    "hljs swift": "Swift",
    "hljs taggerscript": "Tagger Script",
    "hljs tap": "Test Anything Protocol",
    "hljs tcl": "Tcl",
    "hljs tk": "Tcl",
    "hljs thrift": "Thrift",
    "hljs tp": "TP",
    "hljs twig": "Twig",
    "hljs craftcms": "Twig",
    "hljs typescript": "TypeScript",
    "hljs ts": "TypeScript",
    "hljs tsx": "TypeScript",
    "hljs mts": "TypeScript",
    "hljs cts": "TypeScript",
    "hljs vala": "Vala",
    "hljs vbnet": "Visual Basic .NET",
    "hljs vb": "Visual Basic .NET",
    "hljs vbscript": "VBScript",
    "hljs vbs": "VBScript",
    "hljs vbscript-html": "VBScript in HTML",
    "hljs verilog": "Verilog",
    "hljs v": "Verilog",
    "hljs sv": "Verilog",
    "hljs svh": "Verilog",
    "hljs vhdl": "VHDL",
    "hljs vim": "Vim Script",
    "hljs wasm": "WebAssembly",
    "hljs wren": "Wren",
    "hljs x86asm": "Intel x86 Assembly",
    "hljs xl": "XL",
    "hljs tao": "XL",
    "hljs xml": "HTML, XML",
    "hljs html": "HTML, XML",
    "hljs xhtml": "HTML, XML",
    "hljs rss": "HTML, XML",
    "hljs atom": "HTML, XML",
    "hljs xjb": "HTML, XML",
    "hljs xsd": "HTML, XML",
    "hljs xsl": "HTML, XML",
    "hljs plist": "HTML, XML",
    "hljs wsf": "HTML, XML",
    "hljs svg": "HTML, XML",
    "hljs xquery": "XQuery",
    "hljs xpath": "XQuery",
    "hljs xq": "XQuery",
    "hljs xqm": "XQuery",
    "hljs yaml": "YAML",
    "hljs yml": "YAML",
    "hljs zephir": "Zephir",
    "hljs zep": "Zephir"
};

export default langs;